version: '3.8'

services:
  # RabbitMQ
  rabbitmq:
    image: rabbitmq:4.1.0-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - incfactory_default

  # Postgres + pgvector
  kaiten-test-db:
    image: pgvector/pgvector:pg17
    container_name: kaiten-test-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5436:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - incfactory_default

  # Основные сервисы (для разработки - с build)
  assistant:
    build:
      context: .
      dockerfile: services/assistant/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVICE=assistant
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - DB_HOST=kaiten-test-db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
      - incfactory_default
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    depends_on:
      - llm-service
      - processor
      - rabbitmq
      - kaiten-test-db

  llm-service:
    build:
      context: .
      dockerfile: services/llm-service/Dockerfile
    environment:
      - SERVICE=llm-service
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - EMBEDDING_HOST=${EMBEDDING_HOST}
      - EMBEDDING_API_KEY=${EMBEDDING_API_KEY}
      - EMBEDDING_PROVIDER=${EMBEDDING_PROVIDER}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
      - LLM_HOST=${LLM_HOST}
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_PROVIDER=${LLM_PROVIDER}
      - LLM_MODEL=${LLM_MODEL}
      - EMBEDDING_RATE_LIMIT=${EMBEDDING_RATE_LIMIT}
      - LLM_RATE_LIMIT=${LLM_RATE_LIMIT}
      - LLM_MAX_RETRIES=${LLM_MAX_RETRIES}
      - EMBEDDING_MAX_RETRIES=${EMBEDDING_MAX_RETRIES}
      - LLM_RETRY_DELAY=${LLM_RETRY_DELAY}
      - EMBEDDING_RETRY_DELAY=${EMBEDDING_RETRY_DELAY}
      - EMBEDDING_MAX_TEXT_LENGTH=${EMBEDDING_MAX_TEXT_LENGTH}
      - LLM_MAX_TOKENS=${LLM_MAX_TOKENS}
      - LLM_JSON_PARSE_RETRIES=${LLM_JSON_PARSE_RETRIES}
      - RABBITMQ_MAX_DELIVERY_RETRIES=${RABBITMQ_MAX_DELIVERY_RETRIES}
    networks:
      - incfactory_default
    restart: unless-stopped
    depends_on:
      - rabbitmq

  processor:
    build:
      context: .
      dockerfile: services/processor/Dockerfile
    environment:
      - SERVICE=processor
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - DB_HOST=kaiten-test-db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
      - incfactory_default
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - kaiten-test-db

  # Fetcher (запуск по требованию)
  fetcher:
    build:
      context: .
      dockerfile: services/fetcher/Dockerfile
    environment:
      - SERVICE=fetcher
      - KAITEN_HOST=${KAITEN_HOST}
      - KAITEN_API_KEY=${KAITEN_API_KEY}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - SPACE_ID=${SPACE_ID}
      - COLUMN_ID=${COLUMN_ID}
      - LIMIT=${LIMIT}
      - EXCLUDED_COMMENT_AUTHORS=${EXCLUDED_COMMENT_AUTHORS}
      - KAITEN_RATE_LIMIT_RPS=${KAITEN_RATE_LIMIT_RPS}
    networks:
      - incfactory_default
    profiles:
      - fetcher
    restart: "no"
    depends_on:
      - rabbitmq

volumes:
  db:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  incfactory_default:
    external: true
